// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFI3buZEkM3W4eV5QYatWBWa9PCtsKwmk',
    appId: '1:428678315994:web:d15d1726d31cbce2ca8ae3',
    messagingSenderId: '428678315994',
    projectId: 'gerenciador-de-cursos-ffa73',
    authDomain: 'gerenciador-de-cursos-ffa73.firebaseapp.com',
    storageBucket: 'gerenciador-de-cursos-ffa73.firebasestorage.app',
    measurementId: 'G-EB5X5RJT7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWy52aJFFCI70KnwtE91m-bZQ4o-Cyro',
    appId: '1:428678315994:android:3006b59f9f798cd2ca8ae3',
    messagingSenderId: '428678315994',
    projectId: 'gerenciador-de-cursos-ffa73',
    storageBucket: 'gerenciador-de-cursos-ffa73.firebasestorage.app',
  );
}
